### ISSUE TITLE
Include the API that refreshes the explorer so the user can see the new files

### ISSUE THREAD

**Issue by MrPigeontheCoder** [win93-community/windows93-docs#16]
If i recall correctly, there was an api that was something like
`$explorer.refresh(path, callback)`

Could you add that to the documentation?

**Comment by MrPigeontheCoder** [comment]
https://gist.github.com/MrPigeontheCoder/195ed3e2a499d5e12c254b62d281f66e
I made a gist with what i think it was... i kinda forgot

**Comment by stretch07** [comment]
https://github.com/win93-community/windows93-docs/blob/2.4.x/docs/filesystem/explorer/properties/refresh.md
It's been there for a while, I just haven't written documentation for it. The argument is just a simple callback, but I don't actually think it's necessary. The code that is run on the next line should execute immediately after (also we don't want to turn into http://callbackhell.com/)

**Comment by MrPigeontheCoder** [comment]
Oh, ok, thx
