### ISSUE TITLE
APIS documented

### ISSUE THREAD

**Issue by stretch07** [win93-community/windows93-docs#5]
# APIS DOCUMENTED
* [ ] $error
* [ ] $boot
* [ ] $noop
* [ ] $watch
* [ ] $url
* [ ] $maxZ
* [ ] $chain
* [ ] $undo
* [ ] $loop
* [ ] $delegate
* [ ] $io
* [ ] $kernel
* [ ] $route
* [ ] $fullscreen
* [ ] $animate
* [x] $state
* [ ] $selection
* [ ] $ajax
* [ ] $db
* [ ] $store
* [ ] $el
* [ ] $on
* [x] $extend
* [ ] $screenshot
* [ ] $socket
* [ ] $template
* [ ] $archive
* [ ] $key
* [ ] $gamepad
* [ ] $wheel
* [x] $log
* [ ] $cli
* [ ] $box
* [ ] $drag
* [ ] $transition
* [ ] $pos
* [ ] $resize
* [x] $notif
* [ ] $menu
* [ ] $form
* [x] $window
* [x] $alert
* [x] $confirm
* [x] $prompt
* [x] $fs
* [ ] $file
* [ ] $loader
* [ ] $editor
* [x] $audio
* [x] $exe
* [ ] $explorer

# Contribute
we have a long way to go...

**Comment by MrPigeontheCoder** [comment]
I'm helping bruv
